// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abdkffpnaulqzsdyamha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZGtmZnBuYXVscXpzZHlhbWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjY1OTAsImV4cCI6MjA2NzMwMjU5MH0.r9XLVsyGW7fccMLZtjT-XD2cPycYKqSazcYIs4BYWB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});